-- SCHEMA

DROP TABLE IF EXISTS USUARIOS;
DROP TABLE IF EXISTS PSICOLOGOS;
DROP TABLE IF EXISTS CENTROS;

CREATE TABLE USUARIOS (
    ID INTEGER IDENTITY PRIMARY KEY,
    USER_DATA VARCHAR(255) NOT NULL,
    USER_NAME VARCHAR(255) NOT NULL,
    USER_PWD VARCHAR(255) NOT NULL,
    ID_PSIC INTEGER
);

CREATE TABLE PSICOLOGOS (
    ID INTEGER IDENTITY PRIMARY KEY,
    PSIC_DATA VARCHAR(255) NOT NULL,
    PSIC_NAME VARCHAR(255) NOT NULL,
    PSIC_PWD VARCHAR(255) NOT NULL,
    EMPLOYER_ID INTEGER
);

CREATE TABLE CENTROS (
    EMPLOYER_ID INTEGER IDENTITY PRIMARY KEY,
    EMPLOYER_NAME VARCHAR(255) NOT NULL,
    POSTAL_CODE INTEGER NOT NULL
);

-- Tabla que relaciona una fecha con el estado de ánimo de un usuario ese día
CREATE TABLE EMOTIONDATES(
    EMOTION_NAME VARCHAR(255) NOT NULL,
    FECHA DATE NOT NULL,
    USER_ID INTEGER NOT NULL
    --FECHAID VARCHAR(255) PRIMARY KEY (FECHA,USER_ID)
);

CREATE TABLE LIBROS (
    TITULO DATE NOT NULL,
    AUTOR VARCHAR(255) NOT NULL,
    FECHA_PUB DATE NOT NULL,
    EMOCION DATE NOT NULL
);