-- SCHEMA

DROP TABLE IF EXISTS USUARIOS;
DROP TABLE IF EXISTS PSICOLOGOS;
DROP TABLE IF EXISTS CENTROS;

-- EL USERNAME SE CREA COMO USER NAME ELEGIDO + ID PARA EVITAR PROBLEMAS
CREATE TABLE USUARIOS (
    ID INTEGER IDENTITY PRIMARY KEY,
    USER_DATA VARCHAR(255) NOT NULL,
    USER_NAME VARCHAR(255) NOT NULL,
    USER_PWD VARCHAR(255) NOT NULL,
    ID_PSIC INTEGER
);

CREATE TABLE PSICOLOGOS (
    ID INTEGER IDENTITY PRIMARY KEY,
    PSIC_NAME VARCHAR(255) NOT NULL,
    PSIC_PWD VARCHAR(255) NOT NULL,
    EMPLOYER_ID INTEGER
);

CREATE TABLE CENTROS (
    EMPLOYER_ID INTEGER IDENTITY PRIMARY KEY,
    EMPLOYER_NAME VARCHAR(255) NOT NULL,
    POSTAL_CODE INTEGER NOT NULL
);